# Generated by Django 4.1.3 on 2023-02-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creativepay', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timepunch',
            old_name='employee',
            new_name='employee_id',
        ),
        migrations.AddField(
            model_name='timepunch',
            name='employee_name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
